### ISSUE TITLE
Trait attribute does not work with LocalDate type

### ISSUE THREAD

**Issue by Vorobey31415** [Haulmont/jmix-core#102] opened 2021-02-25 15:13 UTC
Jmix 1.0.SNAPSHOT-202.

Steps to reproduce:
1) Create new project
2) Connect to Postgresql and recreate db
3) Add "Audit of creation" trait to User entity
4) Change createdDate type to LocalDate
5) Run application

AR:
Value of column "created_date" = "null" after creating new User. 

ER:
Value of column "created_date" = "current date" after creating new User.

**Comment by dtaimanov** [comment] 2021-03-02 07:09
Duplicate of Haulmont/jmix-core#80

**Closed** 2021-03-02 07:09 UTC
Labels: state: duplicate
